version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.5.0

workflows:
  lint_pack_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: agileware-jp/redmine-plugin
          orb-path: workspace/packed/orb.yml
          requires:
            - orb-tools/pack
          filters:
            branches:
              ignore: master
      - orb-tools/increment:
          orb-ref: agileware-jp/redmine-plugin
          orb-path: packed/orb.yml
          requires:
            - orb-tools/pack
          filters:
            branches:
              only: master
