version: 2.1

orbs:
  redmine-plugin: agileware-jp/redmine-plugin@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@9.1.0
  browser-tools: circleci/browser-tools@1.4.3

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs: # Integration Testing jobs
  test-download-redmine:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          version: '3.4.9'
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if redmine has the downloaded version
          command: |
            egrep "MAJOR.+3" redmine/lib/redmine/version.rb
            egrep "MINOR.+4" redmine/lib/redmine/version.rb
            egrep "TINY.+9" redmine/lib/redmine/version.rb
      - run:
          name: Check if there is a .version file containing the specified version
          command: test "`cat redmine/.version`" = "3.4.9"
  test-download-redmine-supported-min-version:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          version: $REDMINE_MIN_VERSION
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if redmine has the downloaded version
          command: |
            IFS='.' read -ra digits < <(echo "$REDMINE_MIN_VERSION")
            egrep "MAJOR.+${digits[0]}" redmine/lib/redmine/version.rb
            egrep "MINOR.+${digits[1]}" redmine/lib/redmine/version.rb
            egrep "TINY.+${digits[2]}" redmine/lib/redmine/version.rb
      - run:
          name: Check if there is a .version file containing the specified version
          command: test "`cat redmine/.version`" = "$REDMINE_MIN_VERSION"
  test-download-redmine-latest:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          version: latest
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if there is a .version file containing latest version
          command: |
            cat redmine/.version
            test $(cat redmine/.version) = $(
              curl -s https://api.github.com/repos/redmine/redmine/tags |
              jq -r '.[0].name'
            )
  test-download-redmine-supported-max-version:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          version: $REDMINE_MAX_VERSION
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if redmine has the downloaded version
          command: |
            version=$REDMINE_MAX_VERSION

            if [ "$version" == "latest" ]; then
              cat redmine/.version
              test $(cat redmine/.version) = $(
                curl -s https://api.github.com/repos/redmine/redmine/tags |
                jq -r '.[0].name'
              )
            else
              IFS='.' read -ra digits < <(echo "$version")
              egrep "MAJOR.+${digits[0]}" redmine/lib/redmine/version.rb
              egrep "MINOR.+${digits[1]}" redmine/lib/redmine/version.rb
              egrep "TINY.+${digits[2]}" redmine/lib/redmine/version.rb
            fi
  test-download-redmine-latest-tiny-version:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          version: '4.1'
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if there is a .version file containing latest version
          command: |
            test "$(cat redmine/.version)" = "4.1.7"
  test-download-redmica:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          product: 'redmica'
          version: '2.0.0'
          destination: 'wrk'
      - run:
          name: Check if redmica exists
          command: test -f wrk/lib/redmine.rb
      - run:
          name: Check if redmica has the downloaded version
          command: |
            egrep -A 5 "module\s+RedMica" wrk/lib/redmine/version.rb | egrep "MAJOR.+2"
            egrep -A 5 "module\s+RedMica" wrk/lib/redmine/version.rb | egrep "MINOR.+0"
            egrep -A 5 "module\s+RedMica" wrk/lib/redmine/version.rb | egrep "TINY.+0"
      - run:
          name: Check if there is a .version file containing the specified version
          command: test "`cat wrk/.version`" = "2.0.0"
  test-download-redmica-latest:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          product: 'redmica'
          version: latest
          destination: 'wrk'
      - run:
          name: Check if redmica exists
          command: egrep "module\s+RedMica" wrk/lib/redmine/version.rb
      - run:
          name: Check if there is a .version file containing latest version
          command: |
            cat wrk/.version
            test $(cat wrk/.version) = $(
              curl -s https://api.github.com/repos/redmica/redmica/tags |
              jq -r '.[0].name' |
              sed -e 's/^v//'
            )
  test-download-redmica-latest-tiny-version:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          product: 'redmica'
          version: '2.1'
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if there is a .version file containing latest version
          command: |
            test "$(cat redmine/.version)" = "2.1.1"
  test-download-redmine-trunk:
    docker:
      - image: circleci/buildpack-deps:stretch-scm
    steps:
      - redmine-plugin/download-redmine-trunk
      - run:
          name: Check if redmine exists
          command: test -f redmine/lib/redmine.rb
      - run:
          name: Check if there is a .version file containing "trunk"
          command: test "`cat redmine/.version`" = "trunk"
  test-install-plugin:
    executor: orb-tools/ubuntu
    steps:
      - checkout # To resolve ssh problems with git later
      - redmine-plugin/download-redmine:
          version: '3.4.9'
      - redmine-plugin/install-plugin:
          repository: git@github.com:agileware-jp/redmine_work_days.git
      - run:
          name: Check if the plugin was installed
          command: test -f redmine/plugins/redmine_work_days/init.rb
  test-install-self:
    executor: orb-tools/ubuntu
    steps:
      - redmine-plugin/download-redmine:
          version: '3.4.9'
      - redmine-plugin/install-self
      - run:
          name: Check if the repository was added to plugins
          command: test -f redmine/plugins/redmine-plugin-orb/src/@orb.yml
      - run:
          name: Check if Gemfile.local was copied
          command: diff -u redmine/plugins/redmine-plugin-orb/Gemfile.local redmine/Gemfile.local
  test-generate-database_yml:
    executor: redmine-plugin/ruby-mysql
    steps:
      - redmine-plugin/download-redmine:
          version: '3.4.9'
      - redmine-plugin/generate-database_yml
      - run:
          name: Check if the correct database.yml was created
          command: 'egrep "adapter: mysql2" redmine/config/database.yml'
  test-bundle-install-without-Gemfile_local:
    executor:
      name: redmine-plugin/ruby-sqlite3
      ruby_version: '2.6'
    steps:
      - checkout # To resolve ssh problems with git later
      - redmine-plugin/download-redmine:
          version: '4.1.5'
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - run:
          name: Check if Gemfile.local was created
          command: test -f redmine/Gemfile.local
  test-bundle-install-and-rspec:
    executor:
      name: redmine-plugin/ruby-sqlite3
      ruby_version: '2.6'
    steps:
      - checkout # To resolve ssh problems with git later
      - redmine-plugin/download-redmine:
          version: '4.1.7'
      - redmine-plugin/install-plugin:
          repository: git@github.com:agileware-jp/redmine_issue_templates.git
      - run:
          name: Copy Gemfile.local
          command: cp redmine/plugins/redmine_issue_templates/Gemfile.local redmine/
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/rspec:
          plugin: redmine_issue_templates
      - run:
          name: Check if the test result file exists
          command: test -f /tmp/rspec/rspec.xml
      - run:
          name: Check if the coverage result file exists
          command: test -f redmine/coverage/redmine_issue_templates_spec/index.html
  test-bundle-install-and-test:
    executor:
      name: redmine-plugin/ruby-sqlite3
      ruby_version: '2.6'
    steps:
      - checkout # To resolve ssh problems with git later
      - redmine-plugin/download-redmine:
          version: '4.1.7'
      - redmine-plugin/install-plugin:
          repository: git@github.com:agileware-jp/redmine_issue_templates.git
      - run:
          name: Copy Gemfile.local
          command: cp redmine/plugins/redmine_issue_templates/Gemfile.local redmine/
      - redmine-plugin/generate-database_yml
      - redmine-plugin/bundle-install
      - redmine-plugin/test:
          plugin: redmine_issue_templates
  test-build-plugin-assets:
    docker:
      - image: cimg/node:12.18.2
    steps:
      - checkout
      - run:
          name: Set .node-version
          command: echo '12.18.2' > .node-version
      - redmine-plugin/build-plugin-assets:
          plugin_folder: '~/project'
          cache_key_prefix: build-without-docker
      - run:
          name: Check if the built file exists
          command: test -f ~/project/assets/test.js
  test-build-plugin-assets-with-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Set .node-version
          command: echo '12.18.2' > .node-version
      - redmine-plugin/build-plugin-assets:
          plugin_folder: '~/project'
          use_docker: true
          cache_key_prefix: build-with-docker
      - run:
          name: Check if the built file exists
          command: test -f ~/project/assets/test.js


workflows:
  lint-pack-validate-start-tests:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint:
          name: Lint Orb
      - orb-tools/pack:
          name: Pack Orb
          requires:
            - Lint Orb
      - orb-tools/publish-dev:
          name: Publish dev version
          orb-name: agileware-jp/redmine-plugin
          requires:
            - Pack Orb
      - orb-tools/trigger-integration-tests-workflow:
          name: Start integration tests
          requires:
            - Publish dev version
  test-and-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - test-download-redmine
      - test-download-redmine-latest
      - test-download-redmine-latest-tiny-version
      - test-download-redmine-trunk
      - test-download-redmine-supported-max-version:
          context:
            - lychee-ci-environment
      - test-download-redmine-supported-min-version:
          context:
            - lychee-ci-environment
      - test-download-redmica
      - test-download-redmica-latest
      - test-download-redmica-latest-tiny-version
      - test-install-plugin
      - test-install-self
      - test-generate-database_yml
      - test-bundle-install-without-Gemfile_local
      - test-bundle-install-and-rspec
      - test-bundle-install-and-test
      - test-build-plugin-assets
      - test-build-plugin-assets-with-docker

      # publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          orb-name: agileware-jp/redmine-plugin
          publish-version-tag: false
          requires:
            - test-download-redmine
            - test-download-redmine-latest
            - test-download-redmine-latest-tiny-version
            - test-download-redmine-trunk
            - test-download-redmine-supported-max-version
            - test-download-redmine-supported-min-version
            - test-download-redmica
            - test-download-redmica-latest
            - test-download-redmica-latest-tiny-version
            - test-install-plugin
            - test-install-self
            - test-generate-database_yml
            - test-bundle-install-without-Gemfile_local
            - test-bundle-install-and-rspec
            - test-bundle-install-and-test
            - test-build-plugin-assets
            - test-build-plugin-assets-with-docker
          filters:
            branches:
              only: master
